#https://docs.ansible.com/ansible/2.9/modules/docker_swarm_module.html
---
- name: "Install Docker Swarm requirements"
  apt:
    update_cache: true
    name:
      - "python3-docker"

# La variabile "result" è un dictionary che si tiene in memoria, ma su questa singola macchina!
# Quindi poi devo accedere al dictionary di questa macchina!
- name: "Init Swarm on Manager"
  docker_swarm:
    state: present
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_ip'] }}"
  register: result
  when: inventory_hostname == "vagrant-mng01"

- name: "Get join token for Workers"
  set_fact:
    join_token_worker: "{{ hostvars['vagrant-mng01'].result.swarm_facts.JoinTokens.Worker }}"

- name: "Join workers"
  docker_swarm:
    state: join
    join_token: "{{ join_token_worker }}"
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_ip'] }}"
    remote_addrs: "{{ hostvars['vagrant-mng01']['ansible_ip'] }}"
  when:
    - inventory_hostname in ["vagrant-wrk01", "vagrant-wrk02"]
...