version: '3.4'
services:
  app:
    image: nginx:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
        delay: 3s
        order: start-first
        failure_action: rollback
        monitor: 1m
      restart_policy:
        max_attempts: 3
    ports:
      - "8080:8080"