---
services:
  postgresql:
    build:
      context: "./postgresql"
    ports:
      - "7000:7777"
    environment:
      POSTGRES_USER: "mauro"
      POSTGRES_PASSWORD: "prova"
      POSTGRES_DB: "cars"
...