services:
  web:
    image: "ubuntu:latest"
    container_name: "ubuntu-1"
    command: ["sleep", "infinity"]
    volumes:
      - "./my_data:/my_data" # bind
      - "miscellaneous:/my_stuff" # volume
volumes:
  miscellaneous: