---
- name: "Setup Swarm"
  hosts: all
  gather_facts: true
  become: true

  roles:
    - { role: "swarm-docker", tags: "swarm-docker" }
    - { role: "swarm", tags: "swarm" }
    - { role: "swarm-portainer", tags: "swarm-portainer" }
...