Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define('vagrant-mng01') do |current|
    current.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2310, auto_correct: false)
    current.vm.network('forwarded_port', id: 'portainer', guest: 9000, host: 19000, protocol: "tcp", auto_correct: false)
    current.vm.network('forwarded_port', id: 'stack-deploy', guest: 2375, host: 12375, protocol: "tcp", auto_correct: false)
    current.vm.network('private_network', ip: '192.168.56.10')
    current.vm.hostname = 'vagrant-mng01'
  end

  config.vm.define('vagrant-wrk01') do |current|
    current.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2311, auto_correct: false)
    current.vm.network('private_network', ip: '192.168.56.11')
    current.vm.hostname = 'vagrant-wrk01'
  end

  config.vm.define('vagrant-wrk02') do |current|
    current.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2312, auto_correct: false)
    current.vm.network('private_network', ip: '192.168.56.12')
    current.vm.hostname = 'vagrant-wrk02'
  end
end