version: '3.3'
services:
  q_app:
    build:
      context: .
    ports:
      - "3998:80"
    networks:
      - q_net
  q_redis:
    image: redis:latest
    volumes:
    - q_vol:/tmp/prova.txt
    networks:
    - q_net
volumes:
  q_vol:
networks:
  q_net: