version: '3.6'
services:
  qoturnix:
    build: # E' meglio dargli già una immagine compilata perché se la compila lui se ne sbatte del file .dockerignore perché è un tool separato che non legge il dockerigonre! Se invece faccio un "docker image build" questo legge il .dockerigonre e fa la cosa corretta!
      args:
        - UBUNTU=ubuntu@sha256:b060fffe8e1561c9c3e6dea6db487b900100fc26830b9ea2ec966c151ab4c020
      context: .
      target: staging
    working_dir: /data-staging-1
    entrypoint: '/bin/bash'
    command: -c 'sleep infinity'
    ports:
      - '9090:9090'
