services:
  web:
    build: "."
    container_name: "nginx-2"
    extra_hosts:
      - "octopus:host-gateway"

# Locale: python3 -m http.server 8080

# Se faccio dal container: curl http://octopus:8080
# Dove octopus è il gateway della rete nx-2_default

# Se faccio da locale curl http://10.45.0.66:80
# Dove 10.45.0.66 è l'IP del container

