---
services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile
    command: "rails new . --minimal"
    volumes:
      - "..:/app"
      - "bundler_gems:/usr/local/bundle/"
    user: "1000:1000"
volumes:
  bundler_gems:
...