---
services:
  rails:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - "..:/app"
      - "bundler_gems:/usr/local/bundle/"
    user: "1000:1000"
    command: "rails new ."
volumes:
  bundler_gems:
...