---
services:
  rails:
    build: "."
    image: "rails-setup-image:latest"
    container_name: "rails-setup-container"
    user: "1000:1000"
    command: "rails new ."
    volumes:
      - "..:/app"
...