# Immagine:
#  docker build -t test:env . -f Dockerfile-env --no-cache
# Container:
#  docker container rm test_env
#  docker container run --name test_env -it test:env /bin/bash

FROM ubuntu:latest

# Imposto una variabile di ambiente nel container
# Da dento il container se faccio "env" vedo tra le variabili anche questa
ENV MY_NAME="John Doe"
