development:
  adapter: postgresql
  username: mauro
  password: prova
  database: cars
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>
  template: template0
  host: supercars-db-1
  port: 5432