---
- name: "Install Docker requirements"
  apt:
    update_cache: true
    name:
      - "python3-docker"

# https://docs.portainer.io/start/install-ce/server/docker/linux
- name: "Run Portainer in a container"
  docker_container:
    name: "portainer"
    image: "portainer/portainer-ce:latest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    ports:
      - "9000:9000"
    detach: true
    restart: true
...

