---
name: mauro

services:
  app:
    build:
      context: "./app2"
    volumes:
      - "./app2:/app"
      - "bundler_gems:/usr/local/bundle/"
    command: ["bash", "-c", "sleep infinity"]
    networks:
      - "quaglia"
  db:
    build:
      context: "./db"
    networks:
      - "quaglia"

networks:
  quaglia:
    driver: "bridge"

volumes:
  bundler_gems:
...