# Il secrect lo vedo nel container in: /run/secrets/my_secret.
# Non funziona al meglio fuori da Swarm, sono più pensati per uno Swarm.

---
services:
  web:
    image: "ubuntu:latest"
    command: "/bin/bash -c 'cat /run/secrets/my-secrets'"
    secrets:
      - my-secrets

secrets:
  my-secrets:
    file: "./certificate.txt"
...