# Altra prova
---
services:
  web:
    image: "ubuntu:latest"
    command: "/bin/bash -c 'sleep infinity'"
    secrets: # Questo è buono per la sicurezza, perché devo entrare nel container per vedere i valori delle variabili: /var/run/secrets/server.crt
      - source: "server-certificate" # Nome del secret come esiste nella piattaforma.
        target: "server.crt" # Nome del file montato in /run/secrets/
    environment:
      cert: "xyz123" # Questo può essere un problema per la sicurezza perché da Portainer (per esempio) la vedo in chiaro

secrets:
  server-certificate:
    file: "./certificate.txt" # Anche questo non andrebbe bene perché è in chiaro.

# Dovrei creare dei secrect con un "docker secret create"
# E poi usare external: true
# Però diventa il tutto un po' complicato
...
