# E' identico al compose, ma da portainer posso vedere il secret.
# docker stack deploy --compose-file stack.yml web

---
services:
  web:
    image: "ubuntu:latest"
    command: "/bin/bash -c 'sleep infinity'"
    secrets:
      - my-secrets

secrets:
  my-secrets:
    file: "./certificate.txt" # Può essere un problema per la sicurezza perché ilfile deve essere in chiaro

...