# Immagine:
#  docker build -t test:copy . -f Dockerfile-copy --no-cache
# Container:
#  docker container rm test_copy
#  docker container run --name test_copy -it test:copy /bin/bash

FROM ubuntu:latest

# Copia il file locale copy_test.txt nella home del filesystem del container. Questo crea un layer.
COPY ./copy_test.txt .

# Copia il file locale copy_test.txt anche in questo path. Anche questo crea un layer.
COPY ./copy_test.txt ./tmp