Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define('pg-vagrant') do |current|
    #Portainer:   http://localhost:49152/#!/home
    current.vm.network('forwarded_port', id: 'portainer', guest: 9000, host: 49152, protocol: 'tcp', auto_correct: false)
    current.vm.network('forwarded_port', id: 'remote-daemon', guest: 2375, host: 12375, protocol: 'tcp', auto_correct: false)
    current.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2222, auto_correct: false)
    current.vm.hostname = 'pg-vagrant'
    #   current.vm.provision('ansible') do |ansible|
    #  ansible.compatibility_mode = '1.8'
    #  ansible.playbook = "setup.yml"
    # end
  end
end