Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define('vagrant-dck') do |current|
    current.vm.network('forwarded_port', id: 'portainer', guest: 9000, host: 49152, protocol: 'tcp', auto_correct: false)
    current.vm.network('forwarded_port', id: 'remote-daemon', guest: 2375, host: 12375, protocol: 'tcp', auto_correct: false)
    current.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2222, auto_correct: false)
    current.vm.hostname = 'vagrant-dck'
  end
end