# Da browser: http://0.0.0.0:8080/ e vedo arivare il traffico alle repliche sullo swarm.
services:
  web:
    image: "nginx:latest"
    ports:
      - "8080:80"
    deploy:
      mode: "replicated"
      replicas: 3
