FROM ubuntu:latest

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install docker --no-install-recommends && \
    apt-get clean

#FROM alpine:latest

#RUN apk update && \
#    apk add --no-cache bash