# https://docs.docker.com/build/building/multi-platform/#simple-multi-platform-build-using-emulation
# Se lo faccio su Vagrant dopo aver seguito i passi per installare QUMU funziona!

# syntax=docker/dockerfile:1
FROM alpine
RUN uname -m > /arch